repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.2
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

# .pre-commit-config.yamll
- repo: https://github.com/christophmeissner/pytest-pre-commit
  rev: 1.0.0
  hooks:
  - id: pytest
    entry: python -m pytest tests/
    language: system
    always_run: true