services:
  fastapi-app:
    build: .
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/flightbooking
    depends_on:
      - db
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flightbooking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    